#set base image 
FROM zabbix/zabbix-web-nginx-pgsql:centos-latest

ARG mism_version

ENV MISM_VERSION=$mism_version

COPY items.inc.php /usr/share/zabbix/include/
COPY logo-header.svg /usr/share/zabbix/assets/img/
COPY dark-theme.css /usr/share/zabbix/assets/styles/
COPY blue-theme.css /usr/share/zabbix/assets/styles/


