#set base image 
FROM zabbix/zabbix-server-pgsql:centos-latest

USER root 

ARG mism_version

ENV MISM_VERSION=$mism_version

ENV HTTP_PROXY="http://193.56.47.20:8080"
ENV HTTPS_PROXY="http://193.56.47.20:8080"
ENV NO_PROXY="127.0.0.1,localhost,webserver,0.0.0.0:9090,0.0.0.0,ansible,zabbix,zabbix-web,zabbix-server,zabbix-agent,awx,awx_web,awx_task,rabbitmq,postgres,memcached,elasticsearch,kibana,logstash,filebeat,metricbeat,heartbeat,auditbeat,grafana,prometheus,nodeexporter,caddy,cadvisor,alertmanager,172.31.130.224,172.31.60.18,172.31.92.239,172.31.100.156,172.31.60.18,172.31.92.249,172.31.92.222,172.31.92.44,172.31.92.34"

ENV PYTHONWARNINGS="ignore:Unverified HTTPS request"

# security
# COPY zabbix_server.conf /etc/zabbix

WORKDIR /usr/lib/zabbix/externalscripts

RUN yum -y install epel-release && yum clean all
RUN yum -y install gcc
RUN yum -y install openssl
RUN yum -y install python-pip && yum clean all
RUN yum -y update


#RUN yum -y install gammu
RUN pip install --upgrade pip
RUN pip install requests
RUN pip install pycryptodome

# unset proxy for production
ENV HTTP_PROXY=
ENV HTTPS_PROXY=
# except internal hostnames
ENV NO_PROXY="127.0.0.1,localhost,zabbix-web,zabbix-server,zabbix-agent,awx_web,awx_task,rabbitmq,postgres,memcached"

