#set base image 
FROM ansible/awx_web:latest

ARG mism_version

ENV MISM_VERSION=$mism_version

USER root 

#proxy => should be removed in prod env
ENV HTTP_PROXY="http://193.56.47.20:8080"
ENV HTTPS_PROXY="http://193.56.47.20:8080"
ENV NO_PROXY="127.0.0.1,localhost,zabbix,webserver,0.0.0.0:9090,0.0.0.0,ansible,awx,awx_web, awx_task, rabbitmq,postgres,memcached,elasticsearch,kibana,logstash,filebeat,metricbeat,heartbeat,auditbeat,grafana,prometheus,nodeexporter,caddy,cadvisor,alertmanager,172.31.130.224,172.31.60.18,172.31.92.239,172.31.100.156,172.31.60.18,172.31.92.249,172.31.92.222,172.31.92.44,172.31.92.34"

# security
COPY ansible.credentials.py /etc/tower/conf.d/credentials.py
COPY ansible.environment.sh /etc/tower/conf.d/environment.sh
COPY ansible.cors.py /etc/tower/conf.d/cors.py
COPY ansible.SECRET_KEY /etc/tower/SECRET_KEY
COPY ansible.nginx.conf /etc/nginx/nginx.conf

# customization
# to change the logo : 
# 1. docker exec go to /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/ui/static/css/
# 2. cp app.xxx.css to /mnt => /tmp
# 3. bask to host cp /tmp => /var/mism/app.<careful with the name>.css
# 4. change the style at-Layout-topNavItem--logo as needed
COPY app.000e14438f496b569c02.css /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/ui/static/css/
COPY logo-header.svg /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/ui/static/assets/ 
COPY logo-login.svg /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/ui/static/assets/ 
COPY loginModal.partial.html /var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/ui/static/partials/login/loginModal/

# To be done manually from container : RUN yum update
RUN yum install -y nano dnsutils which nmap software-properties-common -y
# git
RUN pip install --upgrade pip --proxy=193.56.47.8:8080

# Incompatible with .py external docker volume files
# Do it with docker exec after removing volumes
# Warning TODO with [root@vm247-1 mism]# docker-compose -f docker-compose-awx.yml build NOT directly with docker exec => lost
# RUN pip install git+https://github.com/ansible/ansible.git@devel
# not used --proxy=193.56.47.8:8080

# Warning : NOT nmap => https://stackoverflow.com/questions/14913153/module-object-has-no-attribute-portscanner
RUN pip install python-nmap
RUN pip install requests
RUN pip install lxml
RUN pip install urllib3
RUN pip install ansible-vault
# RUN pip install ansible-cmdb
RUN pip install pika

# tower-cli install and config
RUN pip install ansible-tower-cli
ENV TOWER_HOST=https://localhost:8052
RUN export TOWER_HOST=https://localhost:8052
ENV TOWER_USERNAME=mism
ENV TOWER_PASSWORD=mismpass
ENV TOWER_VERIFY_SSL=false
ENV TOWER_INSECURE=true
# RUN tower-cli config host https://localhost:8052

# RUN yum -y install python-dev zlib1g-dev libffi-dev libssl-dev libxml2-dev libxslt1-dev 

RUN pip install paramiko --upgrade --proxy=193.56.47.8:8080

#Install netaddr so we can use ipaddr filter in ansible
RUN pip install netaddr --proxy=193.56.47.8:8080

# unset proxy for production
ENV HTTP_PROXY=
ENV HTTPS_PROXY=
# except internal hostnames
ENV NO_PROXY="127.0.0.1,localhost,zabbix-web,zabbix-server,zabbix-agent,awx_web,awx_task,rabbitmq,postgres,memcached"

EXPOSE 8052

WORKDIR /var/lib/awx

