#!/usr/bin/env python
# -*- coding: utf-8 -*-

############################
#
# OpenBMC Collector for Zabbix
#
# This script will be able to collect information from OpenBMC Mipocket
#
# by francine.sauvage@atos.net
#
#

import sys
#import requests
#import urllib
#import urllib3
#from requests.auth import HTTPBasicAuth
import os
import json
import argparse

#urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

from twilio.rest import Client

def send_twilio(from_, to_):
  twilioClient = Client("AC88d8732c4083e977c07ba812dde068a9", "6f288437df4054b32822f039d790b5df")
  sms = twilioClient.messages.create(body = "whatever", from_=from_, to=to_)
  return sms

def main(args):
  parser = argparse.ArgumentParser(description="This script will be able to collect information from OpenBMC Mipocket")
  parser.add_argument("-f", "--from_", dest="from_", help="SMS phone number of the free text server like twilio", required=True)
  parser.add_argument("-t", "--to_", dest="to_", help="destination phone number", required=True)
  args = parser.parse_args()
  res = send_twilio(args.from_, args.to_)
  print(res)

main(sys.argv)