DATABASE_USER=mism
DATABASE_NAME=mism
DATABASE_HOST=awx_postgres
DATABASE_PORT=5432
DATABASE_PASSWORD=mismpass
MEMCACHED_HOST=memcached
RABBITMQ_HOST=rabbitmq
RABBITMQ_DEFAULT_VHOST=awx
RABBITMQ_DEFAULT_USER=mism
RABBITMQ_DEFAULT_PASS=mismpass
AWX_ADMIN_USER=mism
AWX_ADMIN_PASSWORD=mismpass
ANSIBLE_INVENTORY=/var/lib/awx/inventory
#      ANSIBLE_VAULT_PASSWORD_FILE: ansible_password.txt
#      ANSIBLE_INVENTORY_CACHE: yes
TOWER_HOST=https://localhost:8052
TOWER_USERNAME=TOWER_USERNAME:mism
TOWER_PASSWORD=TOWER_PASSWORD:mismpass
TOWER_VERIFY_SSL=TOWER_VERIFY_SSL:"false"
TOWER_INSECURE=TOWER_INSECURE:"true"
http_proxy=${HTTP_PROXY}
https_proxy=${HTTPS_PROXY}
no_proxy=${NO_PROXY}

