#set base image 
FROM ansible/awx_task:latest

USER root

ARG MISM_BULLSEQUANA_EDGE_VERSION
ENV MISM_BULLSEQUANA_EDGE_VERSION=$MISM_BULLSEQUANA_EDGE_VERSION

USER root 

COPY ansible.credentials.py /etc/tower/conf.d/credentials.py
COPY ansible.env /etc/tower/conf.d/environment.sh
COPY ansible.SECRET_KEY /etc/tower/SECRET_KEY

# To be done manually from container : RUN yum update
RUN yum install -y nano which nmap
RUN yum install -y epel-release

RUN pip2 install --upgrade pip 

# Warning : NOT nmap => https://stackoverflow.com/questions/14913153/module-object-has-no-attribute-portscanner
RUN pip2 install python-nmap
RUN pip2 install requests
RUN pip2 install lxml
RUN pip2 install urllib3
RUN pip2 install ansible-vault

# RUN pip install ansible-cmdb
RUN pip2 install pika
RUN pip2 install paramiko --upgrade
#Install netaddr so we can use ipaddr filter in ansible
RUN pip2 install netaddr

WORKDIR /var/lib/awx
