#set base image 
FROM zabbix/zabbix-agent:centos-latest

USER root 

ARG mism_version

ENV MISM_VERSION=$mism_version

ENV PYTHONWARNINGS="ignore:Unverified HTTPS request"

# security
# COPY zabbix_server.conf /etc/zabbix

RUN yum -y install epel-release && yum clean all
RUN yum -y install gcc
RUN yum -y install openssl
RUN yum -y install python-pip && yum clean all
RUN yum -y update

#RUN yum -y install gammu
RUN pip install --upgrade pip
RUN pip install requests
RUN pip install pycryptodome

