ARG REGISTRY=zabbix
ARG BASE_IMAGE_ZABBIX=zabbix-server-pgsql
ARG TAG_ZABBIX=centos-4.4.1

FROM $REGISTRY/$BASE_IMAGE_ZABBIX:$TAG_ZABBIX

#set base image 
#FROM zabbix/zabbix-server-pgsql:centos-4.4.1

USER root 

ENV MISM_BULLSEQUANA_EDGE_VERSION=2.1.3

ENV PYTHONWARNINGS="ignore:Unverified HTTPS request"

# security
# COPY zabbix_server.conf /etc/zabbix

WORKDIR /usr/lib/zabbix/externalscripts

RUN yum -y update && \ 
    yum -y install gcc && \ 
    yum -y install openssl

RUN yum -y install epel-release

RUN yum -y install python-pip && yum clean all

RUN pip install urllib3  && \ 
    pip install requests && \
    pip install pycryptodome && \
    pip install nmap  && \ 
    yum -y update
