ARG REGISTRY=zabbix
ARG BASE_IMAGE_ZABBIX_AGENT=zabbix-agent
ARG TAG_ZABBIX=centos-4.4.1

FROM $REGISTRY/$BASE_IMAGE_ZABBIX_AGENT:$TAG_ZABBIX

USER root 

ENV MISM_BULLSEQUANA_EDGE_VERSION=2.1.6

ENV PYTHONWARNINGS="ignore:Unverified HTTPS request"

# security
# COPY zabbix_server.conf /etc/zabbix

WORKDIR /usr/lib/zabbix/externalscripts

RUN yum -y update && \ 
    yum -y install gcc && \ 
    yum -y install openssl

RUN yum -y install epel

RUN yum -y install --enablerepo="epel" python-pip && yum clean all

RUN pip install urllib3  && \ 
    pip install requests && \
    pip install pycryptodome && \
    pip install nmap  && \ 
    yum -y update


