ARG REGISTRY=ansible
ARG BASE_IMAGE_AWX_TASK=awx_task
ARG TAG_AWX=9.0.1
ARG MISM_BULLSEQUANA_EDGE_VERSION

FROM $REGISTRY/$BASE_IMAGE_AWX_TASK:$TAG_AWX
#set base image 
#FROM ansible/awx_task:9.0.1

USER root

ENV MISM_BULLSEQUANA_EDGE_VERSION=2.1.3

COPY ansible.credentials.py /etc/tower/conf.d/credentials.py
COPY ansible.env /etc/tower/conf.d/environment.sh
COPY ansible.SECRET_KEY /etc/tower/SECRET_KEY

# To be done manually from container : RUN yum update
RUN yum install -y nano which nmap && \
    yum install -y epel-release && \
    yum install -y ansible

# Warning : NOT nmap => https://stackoverflow.com/questions/14913153/module-object-has-no-attribute-portscanner
RUN pip3 install --upgrade pip && \
    pip install python-nmap && \
    pip install requests && \
    pip install lxml && \
    pip install urllib3 && \
    pip install ansible-vault && \
    pip install pika && \
    pip install paramiko --upgrade && \
    pip install pycryptodome && \
    pip install netaddr

WORKDIR /var/lib/awx
