ARG ZABBIX_BULLSEQUANA_EDGE_VERSION
#set base image 
FROM zabbix/zabbix-server-pgsql:$ZABBIX_BULLSEQUANA_EDGE_VERSION

USER root 

ARG MISM_BULLSEQUANA_EDGE_VERSION
ENV MISM_BULLSEQUANA_EDGE_VERSION=$MISM_BULLSEQUANA_EDGE_VERSION

ENV PYTHONWARNINGS="ignore:Unverified HTTPS request"

# security
# COPY zabbix_server.conf /etc/zabbix

WORKDIR /usr/lib/zabbix/externalscripts

RUN yum -y install epel-release && yum clean all
RUN yum -y install gcc
RUN yum -y install openssl
RUN yum -y install python-pip && yum clean all
RUN yum -y update

#RUN yum -y install gammu
RUN pip install --upgrade pip
RUN pip install requests
RUN pip install pycryptodome

