---
- hosts: all
  connection: local
  name: Set Boot Source Network
  gather_facts: False
  vars_files:
    - "{{ ANSIBLE_EXTERNAL_VARS }}"
    - "{{ ANSIBLE_PASSWORDS }}"

  tasks:
  - include_tasks: ../utils/utils_create_token.yml

  - name: set boot source Network
    uri:
      url: https://{{ baseuri }}/xyz/openbmc_project/control/host0/boot/one_time/attr/BootSource
      method: PUT
      validate_certs: no
      headers:
        X-Auth-Token: "{{ x_token }}"
      body_format: json
      body: 
        data: xyz.openbmc_project.Control.Boot.Source.Sources.Network

  - name: get boot source Network
    uri:
      url: https://{{ baseuri }}/xyz/openbmc_project/control/host0/boot/one_time/attr/BootSource
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ x_token }}"
    register: result_boot_mode

  - set_fact:
      boot_mode: "{{ result_boot_mode.json.data }}"

  - name: validate boot source Network
    assert:
      that:
        - boot_mode  == "xyz.openbmc_project.Control.Boot.Source.Sources.Network"
      fail_msg: "Bios Boot Source NOT set to Network"
      success_msg: "The Bios Boot Source is Network"
