#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Atos BullSequana Edge Zabbix Template
# Version 2.0
# Copyright (C) 2019 Atos or its subsidiaries. All Rights Reserved.

# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
#
############################
#
# BullSequana Edge for Zabbix 
# 
# This script decrypts password for BullSequana Edge with PSK zabbix configuration
#
# by francine.sauvage@atos.net
# 
# ./decrypt_psk_password --password=V2eD+VxLkwH2tTsLYS1t6+H+5ERx9FSQ1/BF/iq/5qo=

import os
import sys
import argparse
from openbmc_psk_password import AESCipher

def main(args):
  parser = argparse.ArgumentParser(description="This script decrypts zabbix password for BullSequana Edge")
  parser.add_argument("-p", "--password", dest="password", help="password to encrypt", required=True)
  args = parser.parse_args() 

  if os.path.exists('/etc/zabbix/zabbix_agentd.psk'):
    with open('/etc/zabbix/zabbix_agentd.psk', 'r') as psk_file:
      psk = psk_file.read()
    if not psk:
      return None
    if psk:
      password = AESCipher(args.password).decrypt()
      print(password)
      return password
  return None
  
if __name__ == '__main__':
    main(sys.argv)
