#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
This script decrypts password for BullSequana Edge with PSK zabbix configuration
This script is associated with Atos BullSequana Edge Zabbix Templates

Usage ./decrypt_psk_password --password=V2eD+VxLkwH2tTsLYS1t6+H+5ERx9FSQ1/BF/iq/5qo=

Copyright (C) 2022 Atos

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.
This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with
this program. If not, see <http://www.gnu.org/licenses/>.

All users shall be bound by the terms and 
conditions of the GNU General Public License v3.0  
which are stated extensively at the following address : 
https://www.gnu.org/licenses/gpl-3.0.en.html

"""

__author__ = "Francine Sauvage"
__contact__ = "support@atos.net"
__date__ = "2022/01/12"
__deprecated__ = False
__email__ =  "francine.sauvage@atos.net"
__license__ = "GPLv3"
__status__ = "Production"
__version__ = "2.1.10"
__copyright__ = "Copyright 2022, Atos"
__maintainer__ = "Francine Sauvage"
__credits__ = ["Francine Sauvage"]

import os
import sys
import argparse
from openbmc_psk_password import AESCipher

def main(args):
  parser = argparse.ArgumentParser(description="This script decrypts zabbix password for BullSequana Edge")
  parser.add_argument("-p", "--password", dest="password", help="password to encrypt", required=True)
  args = parser.parse_args() 

  if os.path.exists('/etc/zabbix/zabbix_agentd.psk'):
    with open('/etc/zabbix/zabbix_agentd.psk', 'r') as psk_file:
      psk = psk_file.read()
    if not psk:
      return None
    if psk:
      password = AESCipher(args.password).decrypt()
      print(password)
      return password
  return None
  
if __name__ == '__main__':
    main(sys.argv)
