#!/usr/bin/env python
# -*- coding: utf-8 -*-

############################
#
# OpenBMC for Zabbix
#
# This simple script encrypts password for zabbix with psk
#
# by francine.sauvage@atos.net
#
# ./encrypt_psk_password --password=sdd@atos
import sys
import argparse
from openbmc_psk_password import AESCipher

def main(args):
  parser = argparse.ArgumentParser(description="This script encrypts zabbix password for OpenBMC Mipocket")
  parser.add_argument("-p", "--password", dest="password", help="password to encrypt", required=True)
  args = parser.parse_args() 
  password = AESCipher(args.password).encrypt()        
  if not password:
    print(r"generate a psk key with generate_psk_key_for_zabbix.sh and follow the instructions")
    return None
  print(r"copy/paste generated line to zabbix / Configuration / Hosts / your host / Macros / {$PASSWORD} value : ")
  print(password)
  return password
  
if __name__ == '__main__':
    main(sys.argv)
