#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Atos BullSequana Edge Zabbix Template
# Version 2.0
# Copyright (C) 2019 Atos or its subsidiaries. All Rights Reserved.

# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
#
############################
#
# BullSequana Edge for Zabbix
#
# This script encrypts password for BullSequana Edge with PSK zabbix configuration
#
# by francine.sauvage@atos.net
#
# ./encrypt_psk_password --password=sdd@atos
import sys
import argparse
from openbmc_psk_password import AESCipher

def main(args):
  parser = argparse.ArgumentParser(description="This script encrypts zabbix password for BullSequana Edge")
  parser.add_argument("-p", "--password", dest="password", help="password to encrypt", required=True)
  args = parser.parse_args() 
  password = AESCipher(args.password).encrypt()        
  if not password:
    print(r"generate a psk key with generate_psk_key_for_zabbix.sh and follow the instructions")
    return None
  print(r"copy/paste generated line to zabbix / Configuration / Hosts / your host / Macros / {$PASSWORD} value : ")
  print(password)
  return password
  
if __name__ == '__main__':
    main(sys.argv)
