#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
This script encrypts password for BullSequana Edge with PSK zabbix configuration

Usage ./encrypt_psk_password

Atos BullSequana Edge Zabbix Template

Copyright (C) 2022 Atos

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.
This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with
this program. If not, see <http://www.gnu.org/licenses/>.

All users shall be bound by the terms and 
conditions of the GNU General Public License v3.0  
which are stated extensively at the following address : 
https://www.gnu.org/licenses/gpl-3.0.en.html

"""

__author__ = "Francine Sauvage"
__contact__ = "support@atos.net"
__date__ = "2022/01/12"
__deprecated__ = False
__email__ =  "francine.sauvage@atos.net"
__license__ = "GPLv3"
__status__ = "Production"
__version__ = "2.1.10"
__copyright__ = "Copyright 2022, Atos"
__maintainer__ = "Francine Sauvage"
__credits__ = ["Francine Sauvage"]

import sys
import argparse
from openbmc_psk_password import AESCipher

def main(args):
  parser = argparse.ArgumentParser(description="This script encrypts zabbix password for BullSequana Edge")
  parser.add_argument("-p", "--password", dest="password", help="password to encrypt", required=True)
  args = parser.parse_args() 
  password = AESCipher(args.password).encrypt()        
  if not password:
    print(r"Error: you should generate a psk key with generate_psk_key_for_zabbix.sh and follow the instructions")
    return None
  print("1. Go to Configuration / Hosts / <your host> / Macros")
  print(r"2. Copy and paste {$PASSWORD} value : "+ password)
  return password
  
if __name__ == '__main__':
    main(sys.argv)
