#!/usr/bin/env python
# -*- coding: utf-8 -*-

############################
#
# OpenBMC Reader for Zabbix
#
# This script is a helper for debug
#
# by francine.sauvage@atos.net
#
#
import sys
import os
import argparse

def main(args):
  parser = argparse.ArgumentParser(description="This script is a helper for debug")
  parser.add_argument("-b", "--bmc", dest="bmc", help="bmc to check", required=False)
  args = parser.parse_args() 

  print "debug"

main(sys.argv)
