#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Atos BullSequana Edge Zabbix Template
# Version 2.0
# Copyright (C) 2019 Atos or its subsidiaries. All Rights Reserved.

# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
#
############################
#
# BullSequana Edge Collector for Zabbix
#
# This script collects information from BullSequana Edge devices
#
# by francine.sauvage@atos.net
#
#

import sys
import requests
import urllib
import urllib3
from requests.auth import HTTPBasicAuth
import os
import json
import argparse
from openbmc_psk_password import AESCipher

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

def get_filename(item_to_file, host):
  filename = item_to_file.split("/")
  if not filename or len(filename) < 2:
    raise TypeError('item should be a part of url /xyz/openbmc_project/<item to enumerate>/enumerate : ({item} given)'.format(item=item_to_file))
  if filename[-1] == "enumerate":
    filename = "{host}-{item}.json".format(host=host, item=filename[-2])
  else:
    filename = "{host}-{parent}-{item}.json".format(host=host, parent=filename[-2], item=filename[-1])
  return os.path.join(os.getcwd(), "openbmc", filename)

def write_collect(file_name, json_to_write):
  with open(file_name, 'w') as file_to_write:
    if json_to_write:
      json.dump(json_to_write, file_to_write)
    file_to_write.close()

def main(args):
  parser = argparse.ArgumentParser(description="This script will be able to collect information from BullSequana Edge devices")
  parser.add_argument("-u", "--user", dest="user", help="user name for BMC", required=True)
  parser.add_argument("-p", "--password", dest="password", help="password for BMC", required=True)
  parser.add_argument("-b", "--bmc", dest="bmc", help="IP for the BMC", required=True)
  parser.add_argument("-i", "--item", dest="item", help="item identifier like /xyz/openbmc_project/sensors/enumerate or /xyz/openbmc_project/inventory/system", required=True)
  args = parser.parse_args()  

  if not args.user or not args.password or not args.bmc or not args.item:
    raise TypeError('openbmc_collect() takes 4 arguments ({} given)'.format(len(args) + 1))

  password = args.password.strip()
  decrypted_password = AESCipher(args.password.strip()).decrypt()
  if decrypted_password:
    password = decrypted_password

  uri = "https://{host}{item_url}".format(host=args.bmc.strip(), item_url=args.item)
  timeout = int(os.environ.get('ZBX_TIMEOUT',4)) - 1
  data = {}
  try:
    response = requests.get(uri, auth=HTTPBasicAuth(args.user.strip(), args.password.strip()), verify=False, timeout=timeout)
    data = response.json()
  except requests.exceptions.Timeout:
    # Maybe set up for a retry, or continue in a retry loop
    data["data"] = None
  except requests.exceptions.TooManyRedirects:
    # Tell the user their URL was bad and try a different one
    data["data"] = None
  except requests.exceptions.RequestException as e:
    # catastrophic error. bail.
    data["data"] = None

  filename = get_filename(args.item.strip(), args.bmc.strip())
  write_collect(filename, data["data"])
  print(filename)

main(sys.argv)
